name: CI

on: [pull_request]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: php-actions/composer@v6

      - name: Get all src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - src/**

      - name: Run PHPUnit on changed src file(s)
        if: steps.changed-files-yaml.outputs.src_any_changed == 'true'
        run: |
          phpunit ${{ steps.changed-files-yaml.outputs.src_all_changed_files }}