name: CI

on: [pull_request]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get all src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - src/**

      - name: Run step if src file(s) change
        if: steps.changed-files-yaml.outputs.src_any_changed == 'true'
        run: |
          echo "One or more test file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.src_all_changed_files }}"



#name: PHPUnit
#run-name: PHPUnit
#on: [pull_request]
#
#jobs:
#  run-PHPUnit:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: php-actions/composer@v6
#
#      - name: Get changed files
#        id: changed-files
#        uses: tj-actions/changed-files@v32
#
#      - name: Run PHPUnit on all added files
#        run: |
#          phpunit ${{ steps.changed-files.outputs. modified_files }}
