name: Code Sniffer
run-name: Code Sniffer

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'

      - name: phpcs
        if: steps.changes.outputs.src == 'true'
        uses: php-actions/phpcs@v1
        with:
          filters: |
            src:
              - 'src/**'

#jobs:
#  changes:
#    runs-on: ubuntu-latest
#    outputs:
#      src: ${{ steps.changes.outputs.src }}
#    steps:
#      - uses: actions/checkout@v3
#      - uses: dorny/paths-filter@v2
#        id: changes
#        with:
#          filters: |
#            src:
#              - 'src/**'
#
#  src:
#    needs: changes
#    if: ${{ needs.changes.outputs.src == 'true' }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Validate composer.json and composer.lock
#        run: composer validate
#
#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v3
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-
#
#      - name: Install dependencies
#        run: composer install --prefer-dist --no-progress
#
#      - name: Code Sniffer
#        uses: php-actions/phpcs@v1
#        with:
#          path: src


#permissions:
#  contents: read
#
#jobs:
#  run-code-sniffer:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Validate composer.json and composer.lock
#      run: composer validate
#
#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-
#
#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress
#
#    - name: Code Sniffer
#      uses: php-actions/phpcs@v1
#      with:
#        path: src



