name: Code Sniffer
run-name: Code Sniffer

on: [push]

jobs:
  run-code-sniffer:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          path: src




