name: Changed Files
run-name: Scan Changed Files

on: [pull_request]

jobs:
  run-scan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get all src files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            src/**

      - name: Check Changed src files for the word 'self'
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             if $(grep -Ricw $file -e 'self') > 0; 
             then
                echo "::warning file=$file::$file contains the word 'self':"
                echo -e "$(grep -Rinw $file -e 'self')\n";
             fi
          done







