name: Code Sniffer
run-name: Code Sniffer

on: [pull_request]

jobs:
  run-code-sniffer:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get all src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - src/**

      - name: Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          path: ${{ steps.changed-files-yaml.outputs.src_all_changed_files }}






