name: Changed Files
run-name: Scan Changed Files

on: [pull_request]

jobs:
  run-scan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get all src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - src/**

      - name: Scan changed files for missing semicolon
        run: | 
          for file in ${{ steps.changed-files-yaml.outputs.src_all_changed_files }}; do
            echo "::warning file=$file,line=9::Missing semicolon"
          done








