name: Code Sniffer
run-name: Code Sniffer

on: [pull_request]

jobs:
  run-code-sniffer:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get all src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - src/**

      - name: List Changed files
        run: | 
          echo "Changed files: ${{ steps.changed-files-yaml.outputs.src_all_changed_files }}"







