name: Psalm Security Scan

on: [push, pull_request]

jobs:
  psalm-security-scan:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Psalm Github Actions
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          composer_require_dev: true
          composer_ignore_platform_reqs: true
#
#      - name: Import Security Analysis results into GitHub Security Code Scanning
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: results.sarif