name: AJAX Auth Include Check
run-name: Ensure AJAX files include auth

on:
  pull_request:
    branches:
      - '**'

jobs:
  ajax-auth-check:
    name: Check for missing auth includes in AJAX files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: changes
        run: |
          echo "CHANGED_FILES=$(git diff --name-only origin/main...HEAD | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Scan AJAX files for auth include
        run: |
          echo "Scanning AJAX files for required auth includes..."
          missing_auth=0

          # Define the patterns and human-readable labels
          patterns=(
            "require_once.*auth\.php"
            "new\s+reporting_auth\s*\("
          )
          labels=(
            "Include statement for auth.php (require_once)"
            "Instantiation of reporting_auth class"
          )

          for file in $CHANGED_FILES; do
            if [[ "$file" == *ajax/*.php ]] && [[ -f "$file" ]]; then
              echo "::group::Checking $file..."

              for i in "${!patterns[@]}"; do
                pattern="${patterns[$i]}"
                label="${labels[$i]}"

                match=$(awk '!/^\s*\/\//' "$file" | grep -E "$pattern" || true)

                if [[ -z "$match" ]]; then
                  echo "::error file=$file::Missing required pattern: $label"
                  missing_auth=1
                else
                  echo "::notice file=$file::Found: $label"
                fi
              done
              
              echo "::endgroup::"
            fi
          done

          if [[ $missing_auth -eq 1 ]]; then
            echo "::error::One or more AJAX files are missing required auth includes or checks."
            exit 1
          else
            echo "::notice::All AJAX files passed auth checks."
          fi